### ISSUE TITLE
Get rid of cosmos-sdk dependency

### ISSUE THREAD

**Issue by evgeniy-scherbina** [Kava-Labs/opendb#3]
We have cosmos-sdk dependency due to this code:

```go
import "github.com/cosmos/cosmos-sdk/server/types"

func OpenDB(appOpts types.AppOptions, ...) (dbm.DB, error) {...}
```

We can try to get rid of it, but it will require slight changes in ethermint code

**Comment by pirtleshell** [comment]
Resolved with https://github.com/Kava-Labs/opendb/pull/6
